import os
import customtkinter as ctk

APP_FOLDER        = "F0Cus"
DATABASE_FILENAME   = "database.db"
LOG_FILENAME      = "app.log"
ICON_FILENAME     = "icon.png"

_appdata   = os.getenv("APPDATA", os.path.expanduser("~"))
APP_DIR    = os.path.join(_appdata, APP_FOLDER)
os.makedirs(APP_DIR, exist_ok=True)

DATABASE_PATH = os.path.join(APP_DIR, DATABASE_FILENAME)
LOG_PATH      = os.path.join(APP_DIR, LOG_FILENAME)
ICON_PATH     = os.path.join(os.path.dirname(__file__), ICON_FILENAME)

DEFAULT_SETTINGS: dict = {
    "refresh_interval": 5,
    "restricted_apps": [
        {"name": "Fortnite.exe", "limit": 1800, "action": "popup", "popup_frequency": 300},
        {"name": "netflix.exe",  "limit": 3600, "action": "popup", "popup_frequency": 600},
    ],
    "daily_limit": {"enabled": False, "limit": 7200, "action": "popup", "popup_frequency": 600},
    "language": "english",
}

COLORS: dict[str, str] = {
    "bg":         "#0D0F14",
    "surface":    "#13161E",
    "surface2":   "#1A1E2A",
    "border":     "#252A38",
    "accent":     "#5B8CFF",
    "text":       "#E8EAF0",
    "text_muted": "#6B7280",
    "text_dim":   "#9CA3AF",
    "success":    "#4ADE80",
    "warning":    "#FBBF24",
    "danger":     "#F87171",
}

APP_FONT = "Arial"

DEFAULT_LANGUAGE = "english"

APP_VERSION = "v0.2.3"

TRANSLATIONS = {
    "french": {
        "title": "F0Cus",
        "activity":"Activité",
        "today":"Aujourd'hui",
        "last_7_days":"7 derniers jours",
        "screen_time_today":"Temps d'écran aujourd'hui",
        "time_spend_today":"Temps passé aujourd'hui",
        "details_per_app":"Détail par application",
        "global_view_screen_time":"Vue d'ensemble de votre temps d'écran",
        "daily_activity":"Activité quotidienne",
        "distribution":"Répartition",
        "refresh":"Actualiser",
        "settings":"Paramètres",
        "general_settings":"Paramètres générale",
        "general":"Général",
        "update_time":"Intervalle de rafraîchissement",
        "seconds":"secondes",
        "enable_daily_limit":"Activer la limite journalière",
        "dashboard_label":"Tableau de bord",
        "settings_label":"Paramètres",
        "seven_days":"7 jours",
        "no_data":"Aucune\ndonnée",
        "time_exceeded":"Temps dépassé",
        "take_a_break":"Pensez à faire une pause !",
        "ok_understood":"OK, compris",
        "daily_limit_seconds":"Limite journalière (secondes)",
        "action_popup":"Action : Popup",
        "action_shutdown":"Action : Eteindre l'ordinateur",
        "popup_frequency_seconds":"Frequences de popup (secondes)",
        "restricted_apps_label":"Applications restreintes",
        "add_app_button":"+ Ajouter",
        "save_button":"Sauvegarder",
        "no_restricted_apps":"Aucune application restreinte",
        "reminder":"Rappel :",
        "limit":"Limite",
        "kill_action":"Kill",
        "popup_action":"Popup",
        "restricted_app_title":"Application restreinte",
        "executable_name":"Nom de l'exécutable (.exe)",
        "time_limit_seconds":"Limite de temps (secondes)",
        "action_on_exceed":"Action en cas de dépassement",
        "popup_frequency_label":"Fréquence popup (secondes)",
        "save_app_button":"Enregistrer",
        "error":"Erreur",
        "invalid_values":"Les valeurs sont invalides.",
        "settings_saved":"Paramètres sauvegardés",
        "name_required":"Nom requis.",
        "invalid_numeric_values":"Valeurs numériques invalides.",
        "example_exe":"ex: chrome.exe",
        "limit_word":"Limite :",
        "software_language":"Langue du logiciel"
    },
    "english": {
        "title": "F0Cus",
        "activity": "Activity",
        "today": "Today",
        "last_7_days": "Last 7 days",
        "screen_time_today": "Screen time today",
        "time_spend_today": "Time spent today",
        "details_per_app": "Details per app",
        "global_view_screen_time": "Global screen time overview",
        "daily_activity": "Daily activity",
        "distribution": "Distribution",
        "refresh": "Refresh",
        "settings": "Settings",
        "general_settings": "General settings",
        "general": "General",
        "update_time": "Refresh interval",
        "seconds": "seconds",
        "enable_daily_limit": "Enable daily limit",
        "dashboard_label": "Dashboard",
        "settings_label": "Settings",
        "seven_days": "7 days",
        "no_data": "No\ndata",
        "time_exceeded": "Time exceeded",
        "take_a_break": "Remember to take a break!",
        "ok_understood": "OK, understood",
        "daily_limit_seconds": "Daily limit (seconds)",
        "action_popup": "Action: Popup",
        "action_shutdown": "Action: Shut down computer",
        "popup_frequency_seconds": "Popup frequency (seconds)",
        "restricted_apps_label": "Restricted apps",
        "add_app_button": "+ Add",
        "save_button": "Save",
        "no_restricted_apps": "No restricted apps",
        "reminder": "Reminder:",
        "limit": "Limit",
        "kill_action": "Kill",
        "popup_action": "Popup",
        "restricted_app_title": "Restricted application",
        "executable_name": "Executable name (.exe)",
        "time_limit_seconds": "Time limit (seconds)",
        "action_on_exceed": "Action on exceed",
        "popup_frequency_label": "Popup frequency (seconds)",
        "save_app_button": "Save",
        "error": "Error",
        "invalid_values": "Invalid values.",
        "settings_saved": "Settings saved",
        "name_required": "Name required.",
        "invalid_numeric_values": "Invalid numeric values.",
        "example_exe": "ex: chrome.exe",
        "limit_word": "Limit:",
        "software_language": "Software language"
    },
    "spanish": {
        "title": "F0Cus",
        "activity": "Actividad",
        "today": "Hoy",
        "last_7_days": "Últimos 7 días",
        "screen_time_today": "Tiempo de pantalla hoy",
        "time_spend_today": "Tiempo transcurrido hoy",
        "details_per_app": "Detalle por aplicación",
        "global_view_screen_time": "Vista general del tiempo de pantalla",
        "daily_activity": "Actividad diaria",
        "distribution": "Distribución",
        "refresh": "Actualizar",
        "settings": "Configuración",
        "general_settings": "Configuración general",
        "general": "General",
        "update_time": "Intervalo de actualización",
        "seconds": "segundos",
        "enable_daily_limit": "Activar límite diario",
        "dashboard_label": "Tablero",
        "settings_label": "Configuración",
        "seven_days": "7 días",
        "no_data": "Sin\ndatos",
        "time_exceeded": "Tiempo excedido",
        "take_a_break": "¡Recuerda tomar un descanso!",
        "ok_understood": "Aceptar",
        "daily_limit_seconds": "Límite diario (segundos)",
        "action_popup": "Acción: Ventana emergente",
        "action_shutdown": "Acción: Apagar el equipo",
        "popup_frequency_seconds": "Frecuencia de avisos (segundos)",
        "restricted_apps_label": "Aplicaciones restringidas",
        "add_app_button": "+ Añadir",
        "save_button": "Guardar",
        "no_restricted_apps": "Sin aplicaciones restringidas",
        "reminder": "Recordatorio:",
        "limit": "Límite",
        "kill_action": "Cerrar proceso",
        "popup_action": "Ventana emergente",
        "restricted_app_title": "Aplicación restringida",
        "executable_name": "Nombre del ejecutable (.exe)",
        "time_limit_seconds": "Límite de tiempo (segundos)",
        "action_on_exceed": "Acción al exceder el límite",
        "popup_frequency_label": "Frecuencia de avisos (segundos)",
        "save_app_button": "Guardar",
        "error": "Error",
        "invalid_values": "Valores no válidos.",
        "settings_saved": "Configuración guardada",
        "name_required": "Nombre obligatorio.",
        "invalid_numeric_values": "Valores numéricos no válidos.",
        "example_exe": "ej: chrome.exe",
        "limit_word": "Límite:",
        "software_language": "Idioma del software"
    },
    "chinese": {
        "title": "F0Cus",
        "activity": "活动",
        "today": "今天",
        "last_7_days": "最近7天",
        "screen_time_today": "今日屏幕使用时间",
        "time_spend_today": "今日已使用时长",
        "details_per_app": "应用详情",
        "global_view_screen_time": "屏幕使用时间概览",
        "daily_activity": "每日活动",
        "distribution": "分布",
        "refresh": "刷新",
        "settings": "设置",
        "general_settings": "常规设置",
        "general": "常规",
        "update_time": "刷新间隔",
        "seconds": "秒",
        "enable_daily_limit": "启用每日限制",
        "dashboard_label": "仪表板",
        "settings_label": "设置",
        "seven_days": "7天",
        "no_data": "暂无\n数据",
        "time_exceeded": "时间已超时",
        "take_a_break": "记得休息一下！",
        "ok_understood": "好的，明白了",
        "daily_limit_seconds": "每日限制（秒）",
        "action_popup": "动作：弹窗提示",
        "action_shutdown": "动作：关闭电脑",
        "popup_frequency_seconds": "弹窗频率（秒）",
        "restricted_apps_label": "受限应用",
        "add_app_button": "+ 添加",
        "save_button": "保存",
        "no_restricted_apps": "无受限应用",
        "reminder": "提醒：",
        "limit": "限制",
        "kill_action": "强制停止",
        "popup_action": "弹窗",
        "restricted_app_title": "受限应用",
        "executable_name": "可执行文件名 (.exe)",
        "time_limit_seconds": "时间限制（秒）",
        "action_on_exceed": "超出后的动作",
        "popup_frequency_label": "弹窗频率（秒）",
        "save_app_button": "保存",
        "error": "错误",
        "invalid_values": "数值无效。",
        "settings_saved": "设置已保存",
        "name_required": "必填名称。",
        "invalid_numeric_values": "无效的数值。",
        "example_exe": "例如：chrome.exe",
        "limit_word": "限制：",
        "software_language": "软件语言"
    }
}

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")